// GENERATED by scripts/fetch-station-thumbs.mjs from data/source/station-photos.json. Do not edit by hand.
import type { StationPhoto } from './photos';

export const STATION_PHOTOS: Record<string, StationPhoto> = {};
